START_OF_RECORD=45fbc6d3e05ebd93369ce542e8f2322d||||1f5e7f2748adabf08629a6312ac3bfdd||||
Wellness call made to patient.  States he recently in the hospital for CVA.  Saw his pcp [**Initials (NamePattern4) 1**] [**2022-01-02**] and was put on warfarin 2.5mg.  Patient is nervous about starting a new medication and feeling discouraged about not being able to walk as well as he did before.  Empathetic listening and education provided to patient.  He would like a phone follow up on [**2022-01-14**] in the morning to over how things have been going on new med change and mobility.
||||END_OF_RECORD
START_OF_RECORD=248e844336797ec98478f85e7626de4a||||d3696cfb815ab692407d9362e6f06c28||||
Initial CM care call completed. FCC stated and DOB verified for compliance. Last DOS with PCP notes reviewed. Patient denies any recent ER visits, hospitalizations, or falls. Patient voices having trouble taking his as directed due to high copays. Patient states he is unable to monitor his blood pressure and pulse every morning before taking his Metoprolol due to not having a functioning BP cuff. Patient reports he has no trouble with ADL's, and that his transportation service; [**Doctor Last Name 2**], is working out well. Patient states he has had no appointments with any physician since last DOS. Patient states that he has been referred to a new Endocrinologist per PCP [**Doctor Last Name 3**]. Appointment is scheduled for [**2022-03-15**]. Transportation via [**Doctor Last Name 2**] has already been arranged per patient. Patient is concerned that Endocrinologist will change his diabetic medications. Patient requested follow up call from this CM on [**2022-03-16**]. Patient states he will be volunteering at his church in the AM but will be available to talk around 2pm. This CM will set a follow up reminder for [**2022-03-16**] at 2pm in patient chart. Patient notified that he could pick up his BP cuff at his u;coming appointment with PCP. [**Name10 (NameIs) 4**] patients permission, updated patients preferred pharmacy to Medicap in [**Location (un) 5**], IL, as well as, connecting patient with Medicap via phone transfer to arrange that his prescriptions be moved from present pharmacy. No other concerns, questions, or complaints noted at this time.  HG, LPN
||||END_OF_RECORD
START_OF_RECORD=248e844336797ec98478f85e7626de4a||||eab0141b79354969d1edd234fbc07422||||
CM care call completed. FCC stated and DOB verified for compliance. Last DOS with PCP notes reviewed. Patient denies any recent ER visits, hospitalizations, or falls. Patient voices having trouble taking his insulin as directed due to high copays. Patient states he occasionally feels ill due to uncontrolled blood sugar. Patient states he feels fine at time of care call. Patient encouraged to continue taking his medication as prescribed and testing his sugar with the instructions PCP [**Name9 (PRE) 3**] provided. Patient states he is unable to monitor his blood pressure and pulse every morning before taking his Metoprolol due to not having a functioning BP cuff. Patient reports he has no trouble with ADL's, and that his transportation service; [**Doctor Last Name 2**], is working out well. Patient states he has had no appointments with any physician since last DOS. Patient states that he has been referred to a new Endocrinologist per PCP [**Doctor Last Name 3**]. Appointment is scheduled for [**2022-03-15**]. Transportation via [**Doctor Last Name 2**] has already been arranged per patient. Patient is concerned that Endocrinologist will change his diabetic medications. Patient requested follow up call from this CM on [**2022-03-16**]. Patient states he will be volunteering at his church in the AM but will be available to talk around 2pm. This CM will set a follow up reminder for [**2022-03-16**] at 2pm in patient chart. Patient notified that he could pick up his BP cuff at his upcoming appointment with PCP. [**Name10 (NameIs) 6**] other concerns, questions, or complaints noted at this time. Patient reminded he may contact CM at any time, and CM will return his phone call as soon as possible. With patients permission, updated patients preferred pharmacy to CVS [**Street Address 7**], in [**Location (un) 8**], IL, as well as, connecting patient with CVS via phone transfer to arrange that his prescriptions be moved from present pharmacy. .  HG
||||END_OF_RECORD
START_OF_RECORD=b59c67bf196a4758191e42f76670ceba||||f5e536083a438cec5b64a4954abc17f1||||
Patient contacted by nurse care manager. Verified patient DOB. eligibility verified. FCC statement.   Chart reviewed. CM spoke patient. Care plan and goals reviewed with patient. Patient reports they did obtain a membership to their [**Location (un) 9**] YMCA and have started participating in exercise classes. Patient reports pain is under better control. Patient reports taking pain medication as directed and using alternative methods to control pain. Patient states they have been using warm compresses and Epsom salt soaks. [**Doctor Last Name **] goal created to help with weight loss and to get better control of hypertension. Patient encouraged to continue with goals and keep up the good work! CM will follow up with patient in the upcoming weeks. [**First Name4 (NamePattern1) 10**] [**Last Name (NamePattern1) 11**], CM
||||END_OF_RECORD
START_OF_RECORD=4edaa105d5f[**Telephone/Fax (2) 12**]1951e38c3ad||||ed77eab0b8ff85d0a6a8365df1846978||||
Call to patient. Spoke to [**Last Name (un) 13**] Wisoky. Patient's name and DOB confirmed.  FCC statement made. Patient verbalized he saw Dr. [**Last Name (STitle) 14**] on [**2022-04-26**] for increased edema in lower legs, was prescribed Furosemide 20 mg daily. Patient states he is now out of his medication and needs a refill. Sent message to CM [**Doctor First Name 15**].  Patient instructed on use of medication, to elevate legs when possible and increase walking to 10 minutes. Patient also states having "accidents" and increased urination since starting Furosemide and is embarrassed. Patient educated on use of adult brief/pullup to help while on medication. Patient verbalizes understanding and thankful. Patient denies any difficulty taking medications as prescribed, has made all appointments to doctor and does not require any help with ADL's as lives with his son who helps him.He states he does not have anything preventing him from getting care he needs and has not had any hospitalizations, trips to ER or any falls.  Confirmed patient address and pharmacy correct. Preferred pharmacy is Walgreens on Orange Blossom [**Last Name (LF) 16**], [**First Name3 (LF) 17**].  Patient also states he is borrowing his wife's cane to help steady his walking.  Notified CM [**Doctor First Name 15**] with request to call practice for walker/cane assistive device. 
||||END_OF_RECORD
START_OF_RECORD=e58cc5ca94270acaceed13bc82dfedf7||||a424ded436368e3f9f10da14c23acc85||||
Spoke with pt [**First Name8 (NamePattern2) 18**] [**Last Name (NamePattern1) 19**] today . 2 patient identifiers verified/ FCC statement read.  Chart reviewed, Pt denies recent hospital visits or any falls, No difficulties with daily ADL's at this time and is taking all medications as ordered by MD.  Pt stated she is having a problem with her BP readings accuracy,  she states her numbers are extremely different 150-190/ 50-90;s than her norms 110/70.  She states she is asymptomatic and thinks its her BP cuff because when she checks her BP at [**Company 20**] it comes back normal.  She said she just cant afford a BP cuff right now. she is on a fixed income and has nobody to help her,   Message sent to [**Initials (NamePattern4) **] [**Last Name (NamePattern4) 21**] CM in order to make her aware that pt needs a BP cuff and to send message to practice because insurance will cover one.  Made pt aware that insurance will cover a BP cuff and the pharmacy [**Company 20**] will call her when it is ready for pick up, Confirmed Pharmacy with Pt [**Company 20**] on [**Last Name (un) 22**] st,  [**Location (un) 23**] IL but was unable to place this under preferred pharmacy.  Pt states her A1c's have been within normal range and has had no other problems this month,  She states she is very grateful for all we do. 
||||END_OF_RECORD
START_OF_RECORD=f0935e4cd5920aa6c7c996a5ee53a70f||||f3be5eb7ff15f2013a3b65fbca4bf864||||
Care call to Patient. Patient verified name and DOB. FCC statement made. Patient reports he is "doing much better" this month. Patient reports he has been getting his meals delivered via meal on wheels. Patient reports no hospitalizations or ER visits since last call. No falls reported. Patient's daughter providing transportation to appointments, no recent appointments reported. Declines changes in ADLs. Patient reports he is having a hard time remember to check his blood sugar in the evening which in turn is causing him to miss night time insulin doses. CM educated patient on importance of checking blood sugar as ordered and taking medications as prescribed. CM discussed options for Patient to remind himself to check his blood sugar and take insulin in the evening. Patient is to put a note on his end table beside his chair where he watches the evening news as a reminder to check blood sugar and take insulin. Glucometer is placed in the kitchen beside refrigerator so that patient can dose insulin post checking his blood sugar. CM and Patient also talked about patient keeping a blood sugar log to aid in remember to check his blood sugar. CM to follow up with patient next month. Patient to notify [**Doctor Last Name 24**] or CM if any other issues arise. 
||||END_OF_RECORD
START_OF_RECORD=[**Telephone/Fax (2) 25**]2fc240dd2674a7d063b040||||2377f9eb902f3c5855aca19197689b14||||
Spoke with patient  FCC and HIPAA verified/notified. Patient adhereing to HTN action plan as established by Dr. [**Last Name (STitle) 26**] on his appointment [**2022-05-04**]. Monitoring sodium intake, cooking more fresh foods, exercise 30 mins a [**Doctor Last Name 27**] 5x week. Keep a HTN log.  Attempting to within range of less than 140/90 to 120/80 as established by Dr. [**Last Name (STitle) 26**] per patient. Patient report that blood pressure is coming down (145/95) and that he is able to maintain his scheduled exercise at least 3 days a week. He states that his swollen legs sometimes keep him from exercising.

Will notify CCM [**Doctor First Name 15**] J of progress with HTN action plan as established by Dr. [**Last Name (STitle) 26**].  SB
||||END_OF_RECORD
START_OF_RECORD=226d1f15ecd35f784d2a20c3ecf56d7f||||366ce3dedb69b786dae1aa8d75e4e765||||
Call placed to patient [**First Name8 (NamePattern2) 28**] [**Last Name (NamePattern1) 29**]. HIPAA verified and advised of FCC statement.  Chart reviewed. Patient denies any recent hospital or ER visits, denies any recent falls, denies any difficulty taking medication as prescribed. Denies any difficulty attending appointments, denies any difficulty with ADL's at this time. Patient denies any falls and no further need on medications.  Reviewed with patient goals to help reduce stress and lower hypertension. Patient states that he is now walking at the park across the street from his office on his two 15 minute breaks each [**Doctor Last Name 27**] and upon checking his blood pressure this morning it was 148/80 and that is lower than what he states it was last week at 200/106.  He states his son continues to help with his ADL's. Preferred pharmacy is CVS on 2nd St. [**Location (un) 23**]. Denies needing any refills. Patient states he is going to the Farmer's market this weekend to get produce to follow diet, if hurricane does not hit there. 
||||END_OF_RECORD
START_OF_RECORD=1f3202d820180a39f736f20fce790de8||||430a27748f3853d3745bda9d32419fef||||
Chart reviewed. Current goals reviewed. Care call to the patient. Spoke with the patient. Identity verified and FCC statement made. Patient report that is she is doing so well. She states "I have not taken my medications x 2 weeks". Patient reports she is having difficulty getting to the pharmacy to pick up medications for refills. The patient is monitoring blood sugars and for the past two days reports a fasting blood sugar of 110 and 108 with a postprandial blood sugar of 200 and 196. Patient reports this elevated due to being out of her medications. Patient reports she takes Metformin 500mg twice [**Doctor Last Name 27**] as directed however has not taken in 2 weeks. Patient reports she at times will miss a dose of medications reporting 2-3 times in the past. The patient continues to monitor blood pressures daily and reports no elevations of changes in blood pressures since being out of medications.Patient reports occasional am Dizzyness. Discussed fluid restrictions with patient and patient reports Dr. [**Last Name (STitle) 30**] Cardiology instructed the patient to drink no more than 5 (8oz) glasses of fluids daily. Patient consuming typically 6 glasses of fluids with 4 of them being apple juice. Discussed sugar content of apple juice with the patient.  [**Doctor Last Name **] goal added. Discusses transportation with the patient and patient reports she has her neice assist with follow up scheduled. Patient reports she is followed by  Dr. [**Last Name (STitle) 14**] GI for Acid Reflux with next appointment on [**2022-06-27**]. Patient reports she is not taking Nexium as prescribed by GI. This CM contacted CVSPahramcy and spoke with pharmacist [**Male First Name (un) 31**] whom reports patient has medications available but has not picked up. Discussed home delivery and arrangement made with pharamist for home delivery to start immediately by 6 pm this evening. Patient aware. Call to Dr. [**Last Name (STitle) 14**] Office regarding Nexium noncompliance. Call to Dr. [**Last Name (STitle) 30**] office in regards to patient notifying that the patient has not been taking prescribed Lisinopril 5mg tablet daily for 14 days. CM to follow up with fluid restrictions, daily weights, and diet with next care call. Patient barriers and interventions added to chart.  Following EMR message sent to assigned CM to forward to MD:
Good afternoon,
Our team spoke with Lyric Keeling DOB [**1939-01-19**], Patient informs this nurse that she has been out of all medications x 2 weeks due to inability to get to the pharmacy for refills. CM contacted the pharmacy to arrange for home delivery of medications to initiate today by 6 pm. Patient reports am dizziness and fast blood sugars of 110-108 and postprandial blood sugar of 196-200. Patient to continue to monitor blood pressures and blood sugars ans directed.
Thank you,
[**Signature 32**] Time Doc Health Care Manager
||||END_OF_RECORD
START_OF_RECORD=56352739f59643540a3a6e16985f62c7||||9c4e6233c6d5ff637e7984152a3531d5||||
Chart reviewed. Current goals reviewed. Care call then made to patient. DOB verified. FCC statement verified. Patient states that his last visit to see his PCP doctor, Dr. [**Last Name (STitle) 33**], was on [**2022-04-10**], and that he has not been to any other doctors since this visit. After speaking with the patient and asking if he had any current healthcare issues, he stated that he only has about 5 days left of his Losartan 50mg and Zoloft 20mg medications. Patient stated he has an upcoming appointment to see, Dr. [**Last Name (STitle) 33**], but it's not scheduled until [**2022-06-22**]. Patient also states he would rate his health level a 10, if using a 0-10 scale, (10 meaning feeling the best). Patient also stated that (after verifying his information) he has just recently moved. This CM updated patients address, and also called patients preferred pharmacy, Walgreens [**Street Address 34**], 1-[**Telephone/Fax (2) 35**], and spoke with pharmacy technician, [**Female First Name (un) 36**], who let me know that she will reach out to Dr.[**Last Name (STitle) 37**] office to obtain the prescriptions for the refills of these medications. I called patient back to let him know pharmacy will reach out to doctors office and that I will call him on [**2022-06-16**], after 2 p.m. to make certain he was able to get these medications. 
||||END_OF_RECORD
START_OF_RECORD=01d8bae291b1e[**Telephone/Fax (2) 38**]634ccfa0e||||7690dd4db7a92524c684e3191919eb6b||||
Patient's chart and previous encounters reviewed. Care call made to patient. Spoke with patient. Verified patient's identity and FCC statement made. Patient denies hospitalizations, ER visits, and falls. Patient denies concerns with taking medications as prescribed. Patient is independent with ADLs. Patient does report concerns and barriers with attending doctor appointments at this time, as her daughter is unable to take her to and from appointments due to her new work schedule. Hypertension was discussed with patient. She states she is taking her medications regularly and as p[prescribed. Patient reports that she has set an alarm in her phone that has allowed her to obtain her refills prior to running out. Patient states her most recent blood pressure reading was 120/73 this morning. She states that she continues to follow a low sodium diet and avoids fast food. This CM called Med Transport Center at 1-[**Telephone/Fax (2) 39**] and set up transportation for patient to and from doctor's appointments. Patient made aware and is agreeable to use this transportation service. Patient's address confirmed and communicated with transportation services. Patient was provided with Med Transport Center's phone number, should she have any more questions. Patient made aware that during her next care call, her CM [**Doctor First Name 15**] will confirm that transportation services have been rendered. Patient barriers and interventions have been added. CM will follow up on transportation services at next care call. 
||||END_OF_RECORD
START_OF_RECORD=8fb21ee7a2207526da55a679f0332de2||||1e14bfe2714193e7af5abc64ecbd6b46||||
Reviewed patients chart. Reviewed previous encounter. Care call placed to patient. Spoke with patient. Name and DOB verified by patient. FCC statement made. Pt reports no recent falls or injuries. No recent hospitalizations or ER visits. Patient had follow up with Dr. [**Last Name (STitle) 14**] on [**2022-07-26**]. Patient reports Lasix increased back to 40 mg PO daily in the am. Patient reports lower extremity edema has improved and she has no other side effects at this time. Patient states cardiologist would like to see her again in 3 months. Patient expressed appointment not made. CM to follow up with assisting patient schedule 3 month cardiology appoint on next care call. CM encouraged patient to call if she has any changes or needs anything prior to next call. Patient address confirmed.
||||END_OF_RECORD
START_OF_RECORD=fcdf25d6e191893e705819b177cddea0||||209a38b64aac6816dd61ee8f4286939c||||
Spoke with patient for follow up on Metformin refill. Verified patient full name and DOB. FCC statement. Patient was seen at his providers office and was given refills on his Metformin. Patient stated that he has a follow up/routine appointment with Dr. [**Last Name (STitle) 3**] on [**2022-10-11**] @ 8;30am. Patient states that everything is going well and has no concerns right now. Daughter is still taking him to all appointments and picking up scripts for him. No recent ER/hospitalizations or acute care visits. NO problems with ADL's. CM will reach out next month for the monthly care call. CM will verify that the patients routine/follow up visit is still the same and there has been no change.  CW
||||END_OF_RECORD
START_OF_RECORD=bcbe3365e6ac95ea2c0343a2395834dd||||3ceca2fc13c2fa01d4aed1e552d3a6fb||||
Care call placed to patient. Patient name and DOB verified. FCC statement included. Pt is doing well with no concerns at this time. Patient reports picking up his refill of Nexium 20mg yesterday and is taking it as directed. Patient states he is tolerating the medication well. Patient reports no difficulties with any medication, patient has not fallen or been to the hospital or ER. Patient has not seen any other providers and has no healthcare barriers at this time. Patient informed he may contact CM anytime for assistance or if any questions or concerns may arise. 
||||END_OF_RECORD
START_OF_RECORD=fe70c36866add1572a8e2b96bfede7bf||||799fc232a527e7a7d6435c945083a329||||
Reviewed patient chart & previous encounter. Patient Call, spoke with Patient.  Identifiers and FCC made.  Patient denies any recent ER or Hospital visits  since last spoken too or seen by PCP.   [**Name10 (NameIs) 40**] also denies and recent falls.   Patient states he is still able to drive himself to and from all his appointments.  Patient denies any issues with daily living.  Patient expresses medication barrier during care call on [**2022-07-25**].  Pt claimed  taking his metformin on an empty stomach causes him gastric distress.  CM recommended taking his Meftormin after meal to prevent gastric distress.  Pt stated during follow-up care call today he has been taking his metformin approx 2 hours after eating breakfast each morning and has since not had any issues with gastric distress when taking his meformin.  AS, MA

||||END_OF_RECORD
START_OF_RECORD=4dcae38ee11d3a6606cc6cd636a3628b||||70d355680e628fe1c552221f690d8da4||||
Care call follow up, had patient identify name and dob and FCC statement given. Patient states no hospital visits/stays, no falls or injury's, patient is able to get to all of his appointments. Patient states he does not need any refills at this moment and no changes to his medications have been made.  Patient states he is eating breakfast first and he no longer feels nauseas  after taking medications patient is able to shower, cook, and move around the house with no problems, and patient states that there are nothing that is preventing him to have a better health. 
||||END_OF_RECORD
START_OF_RECORD=b5a1fc[**Telephone/Fax (2) 41**]e448d2ccc5bb9703||||09a630e07af043e4cae879dd60db1cac||||
Chart reviewed. Care call placed to patient. Full name and DOB verified. FCC statement made. Pt was recently in the office on [**07-25**]. Blood sugar was checked. Blood sugar is been stable. Patient checks blood sugar three times fasting in the am, lunch, and after dinner.  Blood sugars range between 115-125, today her blood sugar was 118. Patient uses insulin PRN when blood sugar is elevated. She was unsure of when to follow up with her doctor. CM placed a call to the [**Doctor Last Name **] office and spoke to [**Doctor First Name 42**] @ 3:00pm. 3 month follow up appointment scheduled for [**2022-10-24**] @ 10am. Pt also expressed concern with transportation to appts. CM gave the pt the number for Wisdom Care Transportation, [**Telephone/Fax (2) 43**]. Patient address and phone number verified. CM contacted Wisdom Care and scheduled transportation for [**2022-10-24**] at 9:00am. Patient contacted and informed of future Dr [**Last Name (STitle) 44**] and transportation pick up information. Pt expressed no further concerns or barriers to health care. DL
||||END_OF_RECORD
START_OF_RECORD=dc5c768b5dc76a084531934b34601977||||300ecf93b7224cf439b6de6ee1d6c200||||
Initial care call made to patient, name and dob verified, fcc statement made. Introduced myself to patient as new CCM with phone number [**Telephone/Fax (2) 45**] patient has no problems with medications, just needing refills on lisinopril 20 mg, but currently still has some for a few [**Doctor Last Name 27**], she is also needing lancets for her accu check. Patient also needed new Oncologist [**Doctor Last Name **] [**Name9 (PRE) 46**].Did notify patient that CM will contact her [**Doctor Last Name **] to get her refills and new Oncologist information for her and give her a call back. Patient verbally understood. CM contacted [**Doctor Last Name **] office and spoke with [**Doctor First Name 47**], [**Doctor Last Name **] will send in new script of lancets to cvs pharmacy at [**Street Address 48**] 79936, # [**Telephone/Fax (2) 49**]and attained new Oncology information for patient. CM contacted CVS in regards to lisinopril and spoke with [**Doctor Last Name **], they will go ahead and get her lisinopril refilled and contact patient when it is available for pick up. Patient was notified of the information as above, patient stated she will pick up lisinopril and lancets at CVS.  Patient is able to get to her appointments, patient does not have any difficulties with ADL's and has not been to the hospital or urgent clinics. Information of new CM name and phone number given to patient. 
||||END_OF_RECORD
START_OF_RECORD=2b3bf3eee2475e03885a110e9acaab61||||670eca4ad5de0e0cfcc60ab3dd008095||||
Spoke with patient regarding current blood sugar and high blood pressure.  Patient states "My sugars run around 100-130's every morning".  Denies any new problems with checking blood sugar.  Patient denies problems taking Diabetic medications.  Patient checks blood pressure three times a week.  Average blood pressure readings per patient- 130/90's.  Patient denies any chest pain, dizziness, short of breath, headaches.  Patient expressed concern of running out of his blood pressure medication.  Verified pharmacy name/address/number with patient--Mid South Pharmacy .  Per patient only medication needing refilled at this time is Lisinopril.  Verified the following with the patient\.  Lisinopril 20mg 1 by mouth every am.  Called Mid South Pharmacy to check on refill status-patient has no further refills at this time.  Sent the following direct message to CM [**First Name8 (NamePattern2) 15**] [**Last Name (NamePattern1) 50**] to message [**Hospital 51**] Medical via EMR message to request refill for patient.
Good afternoon
Patient is requesting a refill of Lisinopril 20mg 1 by mouth every am.  Please let us know if there is anything we can do to help.

Patient denied any other questions or concerns at this time.  Encouraged patient to call with any concerns/questions.
 
||||END_OF_RECORD
START_OF_RECORD=1e913e1b06ead0b66e30b6867bf63549||||210192abc6dd9b4f53d7ba4926461e86||||
called pt for care management. HIPAA verified. Advised pt that call is being recorded at this time. Pt states she is doing well with her Diabetes and Hypertebsion. Patient states that her readings for blood sugar and blood pressure remain within normal limits. patient reports a glucose reading from this morning of 95 and a blood pressure reading of 130/80 yesterday evening. Patient was almost out of hr lisinopril the last time we spoke, but picked up her new prescription and has continued her medication regimen. Patient states she has an upcoming appointment in January but unsure of the date as she is not near her calendar at the time. Patient states that she has had issues with her car recently and that her car battery keeps dying. Patient states it has caused her to miss [**First Name (Titles) 52**] [**Last Name (Titles) 53**] and have to reschedule due to the car trouble. I advised patient that there are some transportation resources available and that i would look into it and call her right back with a number so she can call and set up pick ups and drop off. Pt verbalized understanding.
Returned patients call and was able to provide a number for transportation program. Advised pt that the program also assist in transportation for grocery shopping and recreational activities. the program does ask for a $2 suggested donation for one way trips. Pt verbalized understanding and state she will be calling them to set up [**Last Name (Titles) 53**] for pick up. Pt had no further questions or concerns at this time.

||||END_OF_RECORD
START_OF_RECORD=253f7b5d921338af34da817c00f42753||||f892447540d0e840049183faa3109b1b||||
Spoke with patient today for monthly care call. Patient states that overall he has been doing very well. Patient reports that he has done better with checking his blood sugar every morning since putting his glucometer by his coffee pot. Patient states this mornings blood sugar reading was 100. Patient states that he will continue to check every morning and take his diabetes medications as directed. Patient reports that he has started doing aquatic training twice a week for about an hour each class and really enjoys the exercise. Patient states that he feels like it has really helped his joints. Patient has started going to the [**Location (un) 9**] farmers market to get fresh vegatables and fruits. Patient explains that he has really enjoyed the new way of eating with the DASH diet. Patient states that he does allow himself one cheat [**Doctor Last Name 27**] every 2 weeks. Patient states that he has not been able to check his blood pressure routinely because his blood pressure machine is old and worn out. CM provided patient with DME [**Doctor Last Name **] [**Name9 (PRE) 54**] to contact for a new blood pressure machine. Overall patient had no other complaints at this time. Continues to take all medications as directed. Care plan updated and [**Doctor Last Name **] goals reviewed. Patient has completed 2 [**Doctor Last Name 2**] goals to date!
||||END_OF_RECORD
START_OF_RECORD=[**Telephone/Fax (2) 55**]f8f8f3302c2b730728e023||||3c7f7c2dae5b4e1dd398cffb26391a58||||
[**2022-10-10**] -- CM called [**Hospital 51**] Medical Spoke to Dr. [**Last Name (STitle) 56**] nurse to confirm patients appointment on [**11-24**] at 12pm and to follow up on X-ray orders by Dr. [**Last Name (STitle) 56**]. Per nurse patient can have X-ray done the [**Doctor Last Name 27**] of his visit since facility is in the 2nd floor.
Called Veyo to confirm transportation services were scheduled for upcoming
appointments. Spoke to [**Doctor First Name 57**] from Veyo who confirmed patient had arranged transportation services for [**11-10**] but not for [**11-24**]. I was able to arrange transportation for patient for both dates. Patient was advised of appointments dates and times, pt was advised transportation will pick him up 1hr prior to his scheduled appointments. Patient verbalized understanding and agreed to plan

14/01/20 - CM llamó a [**Hospital 51**] Medical [**Last Name (un) 58**] con [**Name Prefix (Prefixes) **] [**Last Name (Prefixes) 59**] del Dr. [**Last Name (STitle) 56**] para confirmar [**Name Prefix (Prefixes) **] [**Last Name (Prefixes) 60**] del [**Last Name (Prefixes) 61**] el [**11-24**] a las 12pm y para hacer seguimiento de las órdenes de [**Last Name (un) 62**] X ordenadas por el Dr. [**Last Name (STitle) 56**], enfermera dice que el [**Last Name (STitle) 61**] puede [**First Name9 (NamePattern2) 63**] [**Last Name (un) 62**] X el día de su [**First Name9 (NamePattern2) 64**] [**Last Name (un) 65**] que las instalaciones están en el [**Last Name (un) 66**] piso.
Llamé a Veyo para confirmar que [**Location 67**] de [**First Name9 (NamePattern2) 68**] [**Last Name (un) 69**] programados para las próximas citas. Hablé con [**Doctor First Name 57**] de Veyo, quien confirmó que el [**Doctor First Name 61**] había organizado servicios de [**Doctor First Name 68**] para el [**11-10**] [**Last Name (un) 70**] no para el [**11-24**]. Pude organizar el [**Month/Year (2) 68**] para el [**Month/Year (2) 61**] para ambas fechas. Se informó [**First Name5 (NamePattern1) **] [**Last Name (NamePattern1) 61**] sobre las fechas y horarios [**Name Prefix (Prefixes) 71**] [**Last Name (Prefixes) 72**], se le informó a [**Last Name (Prefixes) 61**] que el [**Last Name (Prefixes) 68**] lo recogerá 1 hora antes de sus citas programadas. El [**Last Name (Prefixes) 61**] verbalizó [**Name Prefix (Prefixes) **] [**Last Name (Prefixes) 73**]ón 
||||END_OF_RECORD
START_OF_RECORD=9a11883317fde3aef2e2432a58c86779||||ba542f3617078b0be2f95e64e425e190||||
[**2022-10-11**] Called and spoke with patient via phone call. Patient has increased his Lantus Solostar U-100 units to 45 units twice a [**Doctor Last Name 27**]. Due to his recent increase, patient is running out faster than expected. Would like a 90 [**Doctor Last Name 27**] supply refill to be sent to [**Company 74**] Pharmacy in [**Location (un) 75**], TX. Will send a message to his CM, to request a refill for Lantus Solostar U-100 from Dr. [**Last Name (STitle) **], and also have CM follow up in the next few days to confirm refill was approve.-MS

Good Morning,

Our team spoke with patient [**First Name8 (NamePattern2) 76**] [**Last Name (NamePattern1) 77**], DOB [**1934-08-22**], on [**2022-10-11**] at 10:00 AM. Patient reported that since he has increased his Lantus Solostar U-100 45 units twice a [**Doctor Last Name 27**], he is running low. Would like a 90 [**Doctor Last Name 27**] refill to be sent to [**Company 74**] Pharmacy in [**Location (un) 75**], TX.

Thank you,
[**Signature **]

Assigned Care Manager

||||END_OF_RECORD
START_OF_RECORD=14ea0d5b0cf49525d1866cb1e95ada5d||||ac6d3309a61190ccce91186c045cc6dc||||
[**2022-10-11**] Called and spoke with patient via phone call. Patient stated that his blood pressure has improved since our last phone call. Patient stated that his doctor increased his blood pressure medication Losartan to 100 mg once a [**Doctor Last Name 27**]. Advised patient to keep a blood pressure log, and check it three times a [**Doctor Last Name 27**]. Patient stated that he tries to check it at least once or twice a [**Doctor Last Name 27**]. Sometimes it's difficult to check it 3 times a [**Doctor Last Name 27**]. Advised patient that we understood that things come up in life, but try your best to check it 3 times a [**Doctor Last Name 27**] as advised by his physician. [**Name10 (NameIs) 78**] most recent blood pressure was 133/88. Congratulated patient on his blood pressure improving and to keep up the good work. Also spoke with patient regarding his sugars. Patient stated that his sugars have been well under controlled since our last phone call. Stated that his recent sugar reading was 123. I congratulated patient on lowering his sugars. I asked how he is doing it, and stated that he has been cutting back on his pastas, rice. With cutting carbohydrates, patient has also lost 5 lbs. I encouraged patient to continue the good work, and to keep going. Cutting carbs will also improve his sugars. No medications were changed per patient, still taking Metformin and Glipizide. Lastly, I spoke with patient regarding his transportation issues from our previous phone call. Patient stated that he started using [**Location (un) 79**] Transportation and has been able to keep his doctors appointments.-MS
||||END_OF_RECORD
START_OF_RECORD=8e489b4966fe8f703b5be647f1cbae63||||827ccb0eea8a706c4c34a16891f84e7b||||
[**2022-10-31**] Per care call.  Spoke with patient today.  Patient informed me that he is compliant with checking his blood pressure daily, and reported that blood pressure has been within normal limits since last care call.  Patient reports that he has not been compliant with checking his glucose levels 3 times a [**Doctor Last Name 27**] as ordered by his physician. [**Name10 (NameIs) 80**] states to have a barrier of not checking his glucose levels at night because he falls asleep on his recliner.  A [**Doctor Last Name 2**] goal was set up with patient to facilitate his goal of checking glucose 3 times a [**Doctor Last Name 27**].  I advised patient to place his testing supplies next to a small table next to the recliner and simply check his glucose levels and rest right after.  Patient informed me that since last care call, he noted his glucose levels to be within normal limits daily, except during special occasions for example parties.  I advised the patient to always keep his testing [**Doctor First Name 81**] on hand so to monitor glucose levels at parties as well.  Patient informed me that he indeed join recommended [**Doctor Last Name 82**] Sneakers program and is very happy with attending the gym. Patient informed me that he has a Urologist appointment set for [**2022-12-07**] at 1 pm with Dr. [**Last Name (STitle) 14**].  Patient informed me that he has no barriers with attending doctors office as his family members facilitate transportation. Patient denies recent falls or hospitalization.  
||||END_OF_RECORD
START_OF_RECORD=e8dfff4676a47048d6f0c4ef899593dd||||3a3d255db4902a0001b094c2aa24146a||||
Patient was very happy to speak with CM today. Discussed his DM and HTN conditions. He is good on his medications and reports that he is taking his meds as ordered. He voiced a concern that he did not have transportation to get food and wanted to get to the grocery. Provided community transportation number to W Ala Public Transportation @ [**Telephone/Fax (2) 83**] for resolution to dilemna. Patient said he would call to schedule his ride and was extremely grateful for our service. CM will call tomorrow to FU and ensure that we have a resolution. He
||||END_OF_RECORD
START_OF_RECORD=e8dfff4676a47048d6f0c4ef899593dd||||0a2b56600097fa2ea81bfc9774f1baaf||||
Patient reported that he called the resource given to him at last call and was able to get an appointment for a ride today at 3:00 PM [**2022-12-13**]. DS
||||END_OF_RECORD
START_OF_RECORD=842424a1d0595b76ec4fa03c46e8d755||||d8b02a85f7fff3856b9dad807b6d0469||||
I spoke with the patient and confirmed that he is getting meals delivered to his home by Meals on Wheels and he is thankful that the meals that they have been delivering to him are healthy. The patient confirmed that he is taking all of his medications as prescribed and his blood pressure this morning was 118/76. However, the patient mentioned that he has only been keeping a blood pressure log and not a blood glucose log. He confirmed that he has all of his diabetic testing supplies, he just didn't think that he needed to check his blood sugar daily and keep a log of it. [**Doctor Last Name **] goal set for patient. Patient also mentioned that he has an upcoming appointment with his endocrinologist, Dr. [**First Name (STitle) 84**]. 
||||END_OF_RECORD
START_OF_RECORD=3f5ee243547dee91fbd053c1c4a845aa||||f5e298925daba7141e05ef336ae52e30||||
Spoke with patient.  Care plan reviewed.  Patient reports having difficulty getting to the grocery store during the times when his [**Doctor First Name 85**] is travelling for work.  CM offered having meals delivered during the times he doesn't have reliable transportation.  Patient agreed, CM referred patient for meal delivery with Senior Food Box starting [**2023-02-26**].  Patient reports he has not been consistent taking his blood sugar every morning.  Patient states yesterday mornings blood sugar was 106. CM suggested taking blood sugar at the same time as taking blood pressure.  Patient denies any problems with glucometer or medications for diabetes at this time.  Patient also reported he took his blood pressure this morning which was 149/83.  Patient denies any concerns with equipment or medication for hypertension.  Patient preferred pharmacy updated to CVS [**Street Address 86**] 220.  Patient has no further concerns at this time.
||||END_OF_RECORD
